---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "fwiO5ME7qGkqibYG1/8ikggzHrhqEoH+YhNzKpvaKnNzwdZtf/XB66GcUPTGRFzbu76xxZcXb3cf249UP2YWIcQUIYuuh9/IzJlOjkums6DeSLDvCwjwzyVZezbyiF02MazwuXL7yQCRcob4uVspcZJD4DwwXCBOxfv2YuCTJbjkjxvjZTuXpYSg0sSp4GuLDkdIhnLbQ+Oim2MuafOWDKYnasb9r5+3DEGj52ulIgCsRaCpQSDo9Yhf/8A9kTYQVYdm12qeO72VUk5A/F59dY8vtA9ZF82wOz6WtprdUwzngn3RBM1HbN6n5BVImTLb498/r/3FOFddhva+BNDT3/zVYnY/n7VR58PNVZR+ID58BFC0DT7XpElHI+v6ybznESpIwk6gU+wHQNcXauTIazvszLThPKkOl7ZpXp56/c8C1CoF5gHaTuARtxKAxYi/jjU/EfxHlvxM3QBNFQQt3/HtFyDuB8qdtP/YOV3pt1vTrDb1ZUC3E8JhijZ/d6kYu8ZLKl/eSfxgANKwZ077l1qD0zuIJulN+Bec8VOQgZQSpQSwfkHtyI0r2V5dJNpBTiZz5/dQYH41f0gUxPLa9+vqvy3W8U//L8DgLvoo6CuaeManqUxqshBsX6BYga2sJlJhV0TTYdJLvDv5apoExkwc52VcVCu/YRHaNpwxh1k="
  email: false
