---
# tasks file for php

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install php
  package:
    name: "{{ php_packages }}"
    state: present

- name: find used php.ini
  shell: set -o pipefail & {{ php_ini_command }}
  register: php_ini_location
  changed_when: no
  when:
    - php_ini_location is not defined

- name: configure php
  template:
    src: php.ini.j2
    dest: "{{ php_ini_location.stdout | default(php_ini_location) }}"
    mode: "0644"
  notify:
    - restart httpd
