---
# tasks file for php

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install php
  package:
    name: "{{ php_packages }}"
    state: present

- name: configure php
  template:
    src: php.ini.j2
    dest: "{{ php_ini_location }}"
    mode: "0644"
  notify:
    - restart httpd
