---
# tasks file for php
- name: include assert.yml
  include_tasks: assert.yml

- name: install php
  package:
    name: "{{ php_packages }}"
    state: present

- name: configure php
  ini_file:
    dest: "{{ php_ini_location }}"
    section: "{{ item.value.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value.value }}"
    mode: "0644"
  with_dict: "{{ php_settings }}"
  notify:
    - restart httpd
  loop_control:
    label: "{{ item.key }}"
