---
# tasks file for php
- name: install php
  package:
    name: "{{ php_packages }}"
    state: present
  register: php_install_php
  until: php_install_php is succeeded
  retries: 3

- name: configure php
  ini_file:
    dest: "{{ php_ini_location }}"
    section: "{{ item.value.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ php_settings }}"
  notify:
    - restart httpd
  loop_control:
    label: "{{ item.key }}"
