---
# tasks file for php
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_packages }}"

- name: configure php
  ini_file:
    dest: "{{ php_ini_location }}"
    section: "{{ item.value.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ php_settings }}"
  notify:
    - restart httpd
  loop_control:
    label: "{{ item.key }}"
