---
# handlers file for php
- name: restart httpd
  service:
    name: "{{ item }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ php_httpd_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(php_httpd_service[ansible_distribution]
      | default(php_httpd_service['default'] )) }}"

