---
- name: Converge
  hosts: all
  gather_facts: "no"

  roles:
    - role: ansible-role-php

  tasks:
    - name: place phpinfo.php
      copy:
        content: "<?php phpinfo(); ?>"
        dest: /tmp/phpinfo.php

    - name: test /tmp/phpinfo.php
      command: php phpinfo.php
      changed_when: "no"
      register: output

    - name: show output
      debug:
        var: output
