---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - robertdebock.bootstrap
    - robertdebock.scl
    - robertdebock.python_pip
    - robertdebock.httpd
    - ansible-role-php
